env:
  browser: true
  es2021: true
extends: airbnb
parserOptions:
  ecmaVersion: 2021 
  sourceType: module
rules:
  no-unused-expressions:
    - error
    - { allowShortCircuit: true, allowTernary: true } 
  import/no-extraneous-dependencies: off
  react/jsx-props-no-spreading: 'off'
  camelcase: 'off'
  no-console:
    - error
    - { allow: ["warn", "error"] }
  
    
